name: Android CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebugUnitTest

  distribute:
    name: Build & Sign Release
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install specific Build Tools
        run: |
          sdkmanager "build-tools;34.0.0"
          sdkmanager "platforms;android-34"

      - name: Create Keystore File
        run: |
          echo "${{ secrets.SYNC_NOTE_KEYSTORE }}" > keystore.b64
          base64 -d keystore.b64 > sync_note.jks

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Build Release APK and AAB
        run: ./gradlew clean assembleRelease bundleRelease

      - name: Sign APK using apksigner
        run: |
          cd app/build/outputs/apk/release
          $ANDROID_HOME/build-tools/34.0.0/zipalign -v -p 4 app-release.apk app-release-aligned.apk
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign \
            --ks ../../../../sync_note.jks \
            --ks-pass pass:"${{ secrets.KEYSTORE_PASSWORD }}" \
            --ks-key-alias "${{ secrets.ALIAS }}" \
            --key-pass pass:"${{ secrets.ALIAS_PASSWORD }}" \
            --out app-release-signed.apk \
            app-release-aligned.apk

      - name: Sign AAB using jarsigner
        run: |
          cd app/build/outputs/bundle/release
          jarsigner -verbose \
            -keystore ../../../../sync_note.jks \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.ALIAS_PASSWORD }}" \
            app-release.aab \
            "${{ secrets.ALIAS }}"

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-app-release
          path: |
            app/build/outputs/apk/release/app-release-signed.apk
            app/build/outputs/bundle/release/app-release.aab